"""Conversation package — contracts, projection, events, Engine skeleton."""

from .contracts import (
    SCHEMA_FAMILY,
    SCHEMA_VERSION,
    SCHEMA_ID,
    ConversationRequest,
    ConversationContext,
    ConversationDecision,
    ConversationResponse,
    ConversationState,
    DecisionKind,
    LifecyclePhase,
    PresentationHint,
    ErrorClass,
    ValidationError,
    validate,
    validate_request,
    validate_context,
    validate_decision,
    validate_response,
    validate_state,
    to_canonical_json,
    from_canonical_json,
)
from .engine import (
    ConversationEngine,
    ContextBuilder,
    DecisionEngine,
    RequestValidator,
    ResponseBuilder,
    SkeletonNotImplemented,
    StateEmitter,
)
from .events import (
    EVENT_CONVERSATION_STATE_CHANGED,
    ConversationEventJournal,
    ConversationStateChanged,
    get_conversation_event_journal,
    reset_conversation_event_journal_for_tests,
)
from .projection import empty_conversation_section, project_conversation_state

__all__ = [
    "SCHEMA_FAMILY",
    "SCHEMA_VERSION",
    "SCHEMA_ID",
    "ConversationRequest",
    "ConversationContext",
    "ConversationDecision",
    "ConversationResponse",
    "ConversationState",
    "DecisionKind",
    "LifecyclePhase",
    "PresentationHint",
    "ErrorClass",
    "ValidationError",
    "validate",
    "validate_request",
    "validate_context",
    "validate_decision",
    "validate_response",
    "validate_state",
    "to_canonical_json",
    "from_canonical_json",
    "empty_conversation_section",
    "project_conversation_state",
    "EVENT_CONVERSATION_STATE_CHANGED",
    "ConversationEventJournal",
    "ConversationStateChanged",
    "get_conversation_event_journal",
    "reset_conversation_event_journal_for_tests",
    "ConversationEngine",
    "ContextBuilder",
    "DecisionEngine",
    "RequestValidator",
    "ResponseBuilder",
    "SkeletonNotImplemented",
    "StateEmitter",
]
