"""Conversation package — contracts + Snapshot projection (no Engine)."""

from .contracts import (
    SCHEMA_FAMILY,
    SCHEMA_VERSION,
    SCHEMA_ID,
    ConversationRequest,
    ConversationContext,
    ConversationDecision,
    ConversationResponse,
    ConversationState,
    DecisionKind,
    LifecyclePhase,
    PresentationHint,
    ErrorClass,
    ValidationError,
    validate,
    validate_request,
    validate_context,
    validate_decision,
    validate_response,
    validate_state,
    to_canonical_json,
    from_canonical_json,
)
from .projection import empty_conversation_section, project_conversation_state

__all__ = [
    "SCHEMA_FAMILY",
    "SCHEMA_VERSION",
    "SCHEMA_ID",
    "ConversationRequest",
    "ConversationContext",
    "ConversationDecision",
    "ConversationResponse",
    "ConversationState",
    "DecisionKind",
    "LifecyclePhase",
    "PresentationHint",
    "ErrorClass",
    "ValidationError",
    "validate",
    "validate_request",
    "validate_context",
    "validate_decision",
    "validate_response",
    "validate_state",
    "to_canonical_json",
    "from_canonical_json",
    "empty_conversation_section",
    "project_conversation_state",
]
